### ISSUE TITLE
Can't login with other facebook account.

### ISSUE THREAD

**Issue by VikasPawar2112** [HoussemDellai/Facebook-Login-Xamarin-Forms#9]
Title - You login with facebook only where you generated client id. But i want to login with different facebook account. How is possible?Can you please tell us how to do that.Is it possible.

Actual result - Once you generated client id from one account then can't use for another account.

Expected result - Allow to any kind of other facebook account.

**Comment by HoussemDellai** [comment]
Hi Vikas,
You need to login again in order to get a new token.
So you might add a "logout" button to go back to the login screen.

**Comment by VikasPawar2112** [comment]
The probable im facing is that im not being able to login with another account on some other device. The only account its accepting is the one used to generate the client id. Im not receiving new access token for different Facebook accounts. Can you please provide me with some forum discussion or link to documentation that could help? An example code snippet will help too. Thank You!
